-- AlterEnum: DOC staff document types + final payment receipt
ALTER TYPE "FileType" ADD VALUE 'FLIGHT_HOTEL_RESERVATION';
ALTER TYPE "FileType" ADD VALUE 'LETTER_OF_INTENT';
ALTER TYPE "FileType" ADD VALUE 'TRAVEL_PLAN';
ALTER TYPE "FileType" ADD VALUE 'HEALTH_INSURANCE';
ALTER TYPE "FileType" ADD VALUE 'APPOINTMENT_CONFIRMATION';
ALTER TYPE "FileType" ADD VALUE 'FINAL_RECEIPT';
